export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USERS_REQUEST = "USERS_REQUEST";
export const USERS_SUCCESS = "USERS_SUCCESS";
export const USERS_FAIL = "USERS_FAIL";

export const BILLS_REQUEST = "BILLS_REQUEST";
export const BILLS_SUCCESS = "BILLS_SUCCESS";
export const BILLS_FAIL = "BILLS_FAIL";

export const BILL_ADD_REQUEST = "BILL_ADD_REQUEST";
export const BILL_ADD_SUCCESS = "BILL_ADD_SUCCESS";
export const BILL_ADD_FAIL = "BILL_ADD_FAIL";

export const BILL_DELETE_REQUEST = "BILL_DELETE_REQUEST";
export const BILL_DELETE_SUCCESS = "BILL_DELETE_SUCCESS";
export const BILL_DELETE_FAIL = "BILL_DELETE_FAIL";

export const BILL_DONE_REQUEST = "BILL_DONE_REQUEST";
export const BILL_DONE_SUCCESS = "BILL_DONE_SUCCESS";
export const BILL_DONE_FAIL = "BILL_DONE_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";

export const REMOVE_ERROR = "REMOVE_ERROR";
